---

telegram_bot:
    telegram_username: YOUR_TELEGRAM_USERNAME
    telegram_user_id: YOUR_TELEGRAM_USER_ID
    api_token: YOUR_TELEGRAM_BOT_API_TOKEN


api_agent_credentials:
    api_agent_user: YOUR_API_AGENT_USER
    api_agent_password: YOUR_API_AGENT_PASSWORDQ
