---

telegram_bot:
    telegram_username: "YOUR_TELEGRAM_USERNAME"
    telegram_user_id: YOUR_TELEGRAM_ID
    api_token: "YOUR_TELEGRAM_API_TOKEN"
    bot_username: "YOUR_BOT_USERNAME"
    bot_user_id: YOUR_BOT_USER_ID

api_agent_credentials:
    api_agent_user: YOUR_API_AGENT_USER
    api_agent_password: YOUR_API_AGENT_PASSWORD
